version: '3.8'

# Define reusable volumes configuration
x-common-volumes: &common-volumes
  volumes:
    - .:/app
    - /app/node_modules

services:
  frontend:
    build:
      context: .
      target: development
    <<: *common-volumes
    ports:
      - '4200:4200'
    environment:
      - NODE_ENV=development
    command:
      ['npx', 'nx', 'serve', 'restore-photo', '--configuration=development']
    depends_on:
      - backend
      - db

  backend:
    build:
      context: .
      target: development
    <<: *common-volumes
    ports:
      - '3333:3333'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    command: nodemon --exec "nx serve api" --watch ./apps/api
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: restore_photo_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  postgres_data:
