version: '3'
services:
  restore-photo:
    build:
      context: .
      args:
        APP: restore-photo
    ports:
      - '4200:4200'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm start restore-photo
  api:
    build:
      context: .
    ports:
      - '3333:3333'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm start api
  database:
    image: postgres:13
    environment:
      POSTGRES_DB: restore_photo_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
